apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Staging Environment</title>
    </head>
    <body>
        <p>This is a message from Staging Environment!<p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: stg-pacman
